
source 'https://github.com/CocoaPods/Specs.git'#官方仓库地址
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

abstract_target 'BASE_POD' do
    pod 'MBProgressHUD', '~> 1.0'
    pod 'Masonry', '~> 1.0.1'

    # Release Target
    target 'Draw' do
    end

end
